baseURL = 'https://blog.viaodyssey.net/'
languageCode = 'fr-fr'
title = 'Via Odyssey — Blog'
theme = "my-theme"

[params]
rss_summary = false

[outputs]
home = ["HTML", "RSS"]

[outputFormats.RSS]
baseName = "feed"

[services.rss]
limit = 20

[menu]
[[menu.main]]
name = "Videos on Instagram"
url = "https://www.instagram.com/via.odyssey/"
weight = 2

[[menu.main]]
name = "Videos on PeerTube"
url = "https://video.gangneux.net/search?categoryOneOf=6"
weight = 3

[[menu.main]]
name = "Micro Blog"
url = "https://mountains.social/@viaodyssey"
weight = 4

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
